name: Bug Report
description: File a Bug Report
title: "[Bug]: "
labels: ["Bug"]

body:
  - type: textarea
    id: Bug-contents
    attributes:
      label: Bug 설명
      description: Bug에 대한 설명 작성
      placeholder: ex. openAPI 호출 문제
      value: |
         ##  시나리오   
        - 버그 발생 상황에 대한 시나리오를 적어주세요.   
        ## 예상한 결과
        - 예상했던 결과는 어떤 것이었는지 알려주세요.   
        ## 스크린 샷
        - 가능한 경우 문제를 파악하는 데 도움이 되는 스크린 샷을 추가해주세요.
    validations:
      required: true
