name: Feature Report
description: File a Feature Report
title: "[Feature]: "
labels: ["feature"]

body:
  - type: markdown
    attributes:
      value: |
        ## Description
        > 작업할 내용 작성
    validations:
      required: false
  - type: markdown
    id: check-complete-feature
    attributes:
      value: |
        ##  TODO
        - [ ] 구현할 기능
        - [ ] 구현할 기능
    validations:
      required: false
