name: Feature Report
description: File a Feature Report
title: "[Feature]: "
labels: ["feature"]

body:
  - type: textarea
    id: feature-contents
    attributes:
      label: Feature 설명
      description: 작업할 Feature에 대한 설명을 적어주세요.
      placeholder: ex. 사용자 위치기반으로 여행지 추천해주기
    validations:
      required: true
  - type: markdown
    id: check-complete-feature
    attributes:
      description: 상세 기능을 적고, 구현된 기능은 체크해주세요.
      value: |
        [] 구현한 기능
        [] 구현한 기능
    validations:
      required: false
